=== HarveyBlocks/your-batis/YourBatis-core/src/main/resources/org/harvey/batis/builder/xml/xsd/yourbatis-mapper.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://batis.harvey.org/schema/config"
           xmlns="http://batis.harvey.org/schema/config"
           elementFormDefault="qualified">
    <xs:element name="mapper" type="Mapper"/>
    <xs:element name="param" type="TableFieldMap"/>
    <xs:element name="result-map" type="ResultMap"/>
    <xs:element name="result" type="TableFieldMap"/>
    <xs:element name="select" type="ReadSql"/>
    <xs:element name="insert" type="WriteSql"/>
    <xs:element name="update" type="WriteSql"/>
    <xs:element name="delete" type="WriteSql"/>
    <xs:element name="trim" type="Trim"/>
    <xs:element name="where" type="Where"/>
    <xs:element name="set" type="Set"/>
    <xs:element name="foreach" type="Foreach"/>
    <xs:element name="choose" type="Choose"/>
    <xs:element name="when" type="When"/>
    <xs:element name="otherwise" type="Otherwise"/>
    <xs:element name="if" type="If"/>
    <xs:complexType name="Mapper">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="result-map"/>
            <xs:element ref="select"/>
            <xs:element ref="insert"/>
            <xs:element ref="update"/>
            <xs:element ref="delete"/>
        </xs:choice>
        <xs:attribute name="target" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="TableEntityMap">
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="java-entity-type" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="ResultMap">
        <xs:complexContent>
            <xs:extension base="TableEntityMap">
                <xs:sequence>
                    <xs:element ref="result" maxOccurs="unbounded"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="TableFieldMap">
        <xs:attribute name="table-column" type="xs:string" use="required"/>
        <xs:attribute name="java-field" type="xs:string" use="required"/>
        <!-- TODO <xs:attribute name="type-handler" type="xs:string"/>-->
    </xs:complexType>

    <xs:complexType name="ReadSql" mixed="true">
        <xs:complexContent>
            <xs:extension base="SqlType">
                <xs:attribute name="result-map">
                    <xs:simpleType>
                        <xs:list itemType="xs:IDREF"/>
                    </xs:simpleType>
                </xs:attribute>
                <xs:attribute name="result-type" type="xs:string"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="WriteSql" mixed="true">
        <xs:complexContent>
            <xs:extension base="SqlType"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="SqlType" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql">
                <xs:attribute name="method-name" type="xs:ID" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DynamicSql" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element ref="trim"/>
            <xs:element ref="where"/>
            <xs:element ref="set"/>
            <xs:element ref="foreach"/>
            <xs:element ref="choose"/>
            <xs:element ref="if"/>
        </xs:choice>
    </xs:complexType>
    <xs:complexType name="Trim" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql">
                <!--给sql语句拼接的前缀-->
                <xs:attribute name="prefix"/>
                <!--如果prefixOverrides的值成为了SQL最前面的语句, 那么会被去掉-->
                <xs:attribute name="prefixOverrides"/>
                <!--给sql语句拼接的后缀-->
                <xs:attribute name="suffix"/>
                <!--如果suffixOverrides的值成为了SQL最后面的语句, 那么会被去掉-->
                <xs:attribute name="suffixOverrides"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Where" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Set" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Foreach" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql">
                <xs:attribute name="collection" use="required"/>
                <!--创建一个"变量", 代表索引对应元素-->
                <xs:attribute name="item"/>
                <!--创建一个"变量", 代表索引, 对于Map, index就是key-->
                <xs:attribute name="index"/>
                <xs:attribute name="open"/>
                <xs:attribute name="close"/>
                <xs:attribute name="separator"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Choose">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" ref="when"/>
            <xs:element minOccurs="0" ref="otherwise"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="When" mixed="true">
        <xs:complexContent>
            <xs:extension base="If"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="Otherwise" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="If" mixed="true">
        <xs:complexContent>
            <xs:extension base="DynamicSql">
                <!--条件表达式, 为真则本节点内内容起作用-->
                <xs:attribute name="match" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

</xs:schema>

=== HarveyBlocks/your-batis/demo/src/main/resources/org/harvey/batis/demo/mapper/GoodMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>


<mapper xmlns="http://batis.harvey.org/schema/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://batis.harvey.org/schema/config
                            https://batis.harvey.org/schema/config/yourbatis-mapper.xsd"
        target="org.harvey.batis.demo.mapper.GoodMapper"><!--名字写代理接口-->


    <result-map id="GoodMap" java-entity-type="org.harvey.batis.demo.entity.Good">
        <result table-column="id" java-field="id"/>
        <result table-column="name" java-field="name"/>
        <result table-column="price" java-field="price"/>
        <result table-column="stock" java-field="stock"/>
    </result-map>


    <insert method-name="addGood">
        insert into good(name,price,stock)
        values(#{name},#{price},#{stock});
    </insert>
    <insert method-name="addGood2">
        insert into good(name,price,stock)
        values(#{name},#{price},#{stock});
    </insert>


    <delete method-name="delById">
        delete from good where
        id = #{id}
    </delete>

    <delete method-name="delByIds">
        delete from good where
        id in
        <foreach
                collection="array"
                item="id"
                separator=","
                open="("
                close=")">
            #{id}
        </foreach>
        ;
        <!--删除了个寂寞也是删,离谱-->
    </delete>

    <update method-name="update">
        update good
        <set>
            <if match="price!=null">
                price = #{price},
            </if>
            <!--↓这里用and而不是&&-->
            <if match="name!=null and name!= '' ">
                name = #{name},
            </if>
            <if match="stock!=null">
                stock = #{stock},
            </if>
        </set>
        where
        id=#{id}
        ;
        <!--如果good不写id,id默认为0,会删除id = 0 的 商品 不符合-->

    </update>

    <!--id是这一句命令的唯一标识,不能重复-->
    <select method-name="selectAll" result-map="GoodMap"><!--起了别名之后就方便了-->
        select id,name,price,stock from good ;
    </select>

    <select method-name="selectById" result-map="GoodMap">
        select id,name,price,stock
        from good where id like concat('%',#{id},'%');
    </select>

    <select method-name="selectByIds" result-map="GoodMap">
        select id,name,price,stock
        from good where
        <foreach
                collection="array"
                item="id"
                separator=" or ">
            id like concat('%',#{id},'%')
        </foreach>
        ;
    </select>

    <select method-name="selectByName" result-map="GoodMap">
        select id,name,price,stock
        from good where name like concat('%',#{name},'%');
    </select>

    <select method-name="selectByNames" result-map="GoodMap">
        select id,name,price,stock
        from good where
        <foreach
                collection="array"
                item="name"
                separator=" or ">
            name like concat('%',#{name},'%')
        </foreach>
        ;
    </select>

    <select method-name="selectByPrices" result-map="GoodMap">
        select id,name,price,stock
        from good
        <where>
            <![CDATA[
                price<=#{high} and price >= #{low}
            ]]>
        </where>
    </select>

    <select method-name="selectByPrice" result-map="GoodMap">
        select id,name,price,stock
        from good
        <where>
            price = #{price}
        </where>
    </select>

    <select method-name="selectByStocks" result-map="GoodMap">
        select id,name,price,stock
        from good where <![CDATA[
            stock >= #{low} and stock <= #{high}
        ]]>;
    </select>

    <select method-name="selectByStock" result-map="GoodMap">
        select id,name,price,stock
        from good where stock = #{stock}
    </select>

    <select method-name="selectByCondition" result-map="GoodMap">

        select id,name,price,stock
        from good
        <where>
            <if match="price!=null">
                price = #{price}
            </if>
            <!--↓这里用and而不是&&-->
            <if match="name!=null and name!= '' ">
                or name like #{name}
            </if>
            <!--
              这里的语句都是接字符串
             -->
            <if match="stock!=null">
                or stock = #{stoke}
            </if>
        </where>

    </select>

    <!--已弃用-->
    <select method-name="orderByAsc" result-map="GoodMap">
        select id,name,price,stock
        from good order by
        <choose>
            <when match="table-column=='STOCK'">
                stock
            </when>
            <when match="table-column=='PRICE'">
                price
            </when>
            <when match="table-column=='NAME'">
                name
            </when>
            <otherwise>
                id
            </otherwise>
        </choose>
        asc
        ;
    </select>

    <!--已弃用-->
    <select method-name="orderByDesc" result-map="GoodMap">
        select id,name,price,stock
        from good order by
        <choose>
            <when match="table-column=='STOCK'">
                stock
            </when>
            <when match="table-column=='PRICE'">
                price
            </when>
            <when match="table-column=='NAME'">
                name
            </when>
            <otherwise>
                id
            </otherwise>
        </choose>
        desc
    </select>

    <select method-name="orderBy" result-map="GoodMap">
        select id,name,price,stock
        from good order by
        <foreach collection="rules"
                 item="rule"
                 separator=",">
            ${rule}
        </foreach>
    </select>

    <select method-name="dividePage" result-map="GoodMap">
        select id,name,price,stock
        from good limit #{start},#{len};
    </select>


    <select method-name="orderThenPage" result-map="GoodMap">
        select id,name,price,stock
        from good order by
        <choose>
            <when match="table-column=='STOCK'">
                stock
            </when>
            <when match="table-column=='PRICE'">
                price
            </when>
            <when match="table-column=='NAME'">
                name
            </when>
            <otherwise>
                id
            </otherwise>
        </choose>
        <choose>
            <when match="isDesc=='true'">
                desc
            </when>
            <otherwise>
                asc
            </otherwise>
        </choose>
        limit #{start},#{len};
    </select>

</mapper>

=== HarveyBlocks/your-batis/demo/src/main/resources/org/harvey/batis/demo/mapper/BillMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>

<mapper xmlns="http://batis.harvey.org/schema/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://batis.harvey.org/schema/config
                            https://batis.harvey.org/schema/config/yourbatis-mapper.xsd"
        target="org.harvey.batis.demo.mapper.BillMapper"><!--名字写代理接口-->


    <result-map id="BillMap" java-entity-type="org.harvey.batis.demo.entity.Bill">
        <result table-column="id" java-field="id"/>
        <result table-column="bill_id" java-field="id"/>
        <result table-column="gb_bill_id" java-field="id"/>
        <result table-column="union_price" java-field="price"/>
        <result table-column="customer_id" java-field="customerId"/>
        <result table-column="customer" java-field="customerId"/>
        <result table-column="bill_date" java-field="billDate"/>
        <result table-column="union_count" java-field="count"/>
    </result-map>
    <!---->
    <result-map id="GoodMap_" java-entity-type="org.harvey.batis.demo.entity.Good">
        <result table-column="id" java-field="id"/>
        <result table-column="name" java-field="name"/>
        <result table-column="price" java-field="price"/>
        <result table-column="stock" java-field="stock"/>
    </result-map>
    <insert method-name="addBill">
        insert into bill(customer_id,bill_date)
        values(#{customerId},#{billDate});
    </insert>
    <insert method-name="addGoods">
        insert into good_bill(bill_id,good_id,count)
        value
        <foreach
                collection="list"
                item="each"
                separator=",">
            (#{each.billId},#{each.goodId},#{each.count})
        </foreach>
    </insert>

    <delete method-name="delById">
        delete from bill where
        id = #{id}
    </delete>

    <delete method-name="delByIds">
        delete from bill where
        id in
        <foreach
                collection="array"
                item="id"
                separator=","
                open="("
                close=")">
            #{id}
        </foreach>
        ;
        <!--删除了个寂寞也是删,离谱-->
    </delete>

    <update method-name="update">
        update bill
        <set>
            <!--↓这里用and而不是&&-->
            <if match="customerId!=null and customerId!= '' ">
                customer_id = #{customerId},
            </if>
            <if match="billDate!=null">
                bill_date = #{billDate}
            </if>
        </set>
        where
        id=#{id}
        ;
        <!--如果good不写id,id默认为0,会删除id = 0 的 商品 不符合-->
    </update>

    <update method-name="updateByMessage">
        update bill
        <set>
            <!--↓这里用and而不是&&-->
            <if match="customerId!=null and customerId!= '' ">
                customer_id = #{customerId},
            </if>
            <if match="billData!=null and billData!=''">
                bill_date = #{billDate},
            </if>
        </set>
        where
        id=#{id}
        ;
        <!--如果good不写id,id默认为0,会删除id = 0 的 商品 不符合-->

    </update>


    <!--

    SELECT gb.bill_id as bill_id,
b.customer_id as customer_id,
b.bill_date as bill_date,
SUM(gb.count) AS union_count,
SUM(gb.count * g.price) AS union_price
FROM good_bill gb
JOIN bill b ON b.id = gb.bill_id
JOIN good g ON g.id = gb.good_id
GROUP BY gb.bill_id;
    -->
    <!--id是这一句命令的唯一标识,不能重复-->
    <select method-name="selectAll" result-map="BillMap"><!--起了别名之后就方便了-->
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        GROUP BY gb.bill_id;
    </select>


    <select method-name="selectById" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        where bill_id like concat('%',#{id},'%')
        GROUP BY gb.bill_id;
    </select>

    <select method-name="selectByIds" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        where
        <foreach
                collection="array"
                item="id"
                separator=" or ">
            bill_id like concat('%',#{id},'%')
        </foreach>
        GROUP BY gb.bill_id;
    </select>


    <select method-name="selectByCustomerId" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        where (select b.customer_id
        from bill b
        where b.id = gb.bill_id
        ) like concat('%',#{customerId},'%')
        GROUP BY gb.bill_id;
    </select>

    <select method-name="selectByCustomerIds" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        where
        <foreach
                collection="array"
                item="customerId"
                separator=" or ">
            (select b.customer_id
            from bill b
            where b.id = gb.bill_id
            ) like concat('%',#{customerId},'%')
        </foreach>
        GROUP BY gb.bill_id
    </select>

    <!--
SELECT gb.bill_id as bill_id,
b.customer_id as customer_id,
b.bill_date as bill_date,
SUM(gb.count) AS union_count,
SUM(gb.count * g.price) AS union_price
FROM good_bill gb
JOIN bill b ON b.id = gb.bill_id
JOIN good g ON g.id = gb.good_id
GROUP BY gb.bill_id;
    -->

    <select method-name="orderByAsc" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        GROUP BY gb.bill_id
        order by
        <choose>
            <when match="column == 'COUNT'">
                count
            </when>
            <when match="column == 'CUSTOMER_ID'">
                customer
            </when>
            <when match="column == 'PRICE'">
                union_price
            </when>
            <when match="column == 'BILL_DATE'">
                bill_date
            </when>
            <otherwise>
                gb.bill_id
            </otherwise>
        </choose>
        asc;
    </select>
    <select method-name="orderByDesc" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        GROUP BY gb.bill_id
        order by
        <choose>
            <when match="column == 'COUNT'">
                count
            </when>
            <when match="column == 'CUSTOMER_ID'">
                customer
            </when>
            <when match="column == 'PRICE'">
                union_price
            </when>
            <when match="column == 'BILL_DATE'">
                bill_date
            </when>
            <otherwise>
                gb.bill_id
            </otherwise>
        </choose>
        desc;
    </select>

    <select method-name="dividePage" result-map="BillMap">
        SELECT gb.bill_id as bill_id,
        b.customer_id as customer_id,
        b.bill_date as bill_date,
        SUM(gb.count) AS union_count,
        SUM(gb.count * g.price) AS union_price
        FROM good_bill gb
        JOIN bill b ON b.id = gb.bill_id
        JOIN good g ON g.id = gb.good_id
        GROUP BY gb.bill_id
        limit #{start},#{len};
    </select>

    <select method-name="selectGoods" result-map="GoodMap_">
        select g.id, g.name, g.price, g.stock
        from good g
        where g.id in (select gb.good_id
        from good_bill gb
        where gb.bill_id like concat('%',#{billId},'%'));
    </select>

</mapper>

=== HarveyBlocks/your-batis/demo/src/main/resources/org/harvey/batis/demo/mapper/EmployeeMapper.xml
<?xml version="1.0" encoding="UTF-8" ?>

<mapper xmlns="http://batis.harvey.org/schema/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://batis.harvey.org/schema/config
                            https://batis.harvey.org/schema/config/yourbatis-mapper.xsd"
        target="org.harvey.batis.demo.mapper.EmployeeMapper"><!--名字写代理接口-->

    <result-map id="EmployeeResultMap" java-entity-type="org.harvey.batis.demo.entity.Employee">
        <result table-column="id" java-field="id"/>
        <result table-column="first_name" java-field="firstName"/>
        <result table-column="firstName" java-field="firstName"/>
        <result table-column="name" java-field="firstName"/>
    </result-map>
    <!--id是这一句命令的唯一标识,不能重复-->
    <select method-name="selectAll" result-map="EmployeeResultMap">
        <!--起了别名之后就方便了-->
        SELECT id,
        name as first_name
        FROM tb_employee
    </select>
    <select method-name="select" result-map="EmployeeResultMap">
        <!--起了别名之后就方便了-->
        SELECT id,
        name as first_name
        FROM tb_employee where id=#{id} and name=#{firstName}
    </select>
    <select method-name="selectById"
            result-map="EmployeeResultMap EmployeeResultMap EmployeeResultMap EmployeeResultMap">
        <!--起了别名之后就方便了-->
        SELECT id,
        name as firstName
        FROM tb_employee where id=#{id};
        SELECT id,
        name as firstName
        FROM tb_employee where id=#{id};
        SELECT id,
        name as firstName
        FROM tb_employee where id=#{id};
        <if match="id==1">
            SELECT id,
            name as firstName
            FROM tb_employee where id=#{id};
        </if>
    </select>
    <select method-name="selectByIds" result-map="EmployeeResultMap">
        <!--起了别名之后就方便了-->
        SELECT id,
        name
        FROM tb_employee where id in
        <foreach collection="ids"
                 separator="," open="(" close=")" item="id" index="i">
            #{ id }
        </foreach>
        ;
    </select>
    <delete method-name="delById">
        delete from tb_employee where id=#{id} ;
    </delete>
    <!--
    List<Employee> orderByAsc(@Param("column") String column);
    List<Employee> orderByDesc(@Param("column") String column);
    List<Employee> dividePage(@Param("start") int start, @Param("len") int len);
    int getLen();
    int addEmployee(Employee employee);
    int delById(int id);
    int delByIds(int[] ids);
    int updateByMessage(@Param("id") int id, @Param("customerId") int customerId, @Param("employeeDate") Date employeeDate);
    int update(Employee employee);-->
</mapper>
