=== HarveyBlocks/your-batis/YourBatis-core/src/main/resources/YourBatis-config.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://batis.harvey.org/schema/config"
           xmlns="http://batis.harvey.org/schema/config"
           elementFormDefault="qualified">
    <xs:element name="url" type="Url"/>
    <xs:element name="auth" type="Authorization"/>
    <xs:element name="database" type="DatabaseConfiguration"/>
    <xs:element name="data-source" type="DataSource"/>
    <xs:element name="config" type="Config"/>


    <xs:complexType name="Url">
        <xs:sequence>
            <xs:element name="database-name" type="xs:string"/>
            <xs:element name="host" type="xs:string"/>
            <xs:element name="port" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="serverTimezone" type="xs:string" default="UTC"/>
        <xs:attribute name="useSSL" type="xs:boolean" default="false"/>
    </xs:complexType>
    <xs:complexType name="Authorization">
        <xs:sequence>
            <xs:element name="username" type="xs:string"/>
            <xs:element name="password" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="DatabaseConfiguration">
        <xs:sequence>
            <xs:element ref="url"/>
            <xs:element ref="auth"/>
        </xs:sequence>
        <xs:attribute name="driver-class" type="xs:string" default="com.mysql.cj.jdbc.Driver"/>
    </xs:complexType>

    <xs:complexType name="DataSource">
        <xs:sequence>
            <xs:element name="initialSize" type="xs:integer" minOccurs="0"/>
            <xs:element name="maxActive" type="xs:integer" minOccurs="0"/>
            <xs:element name="maxWaitMillion" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="initialSize" type="xs:integer" default="5"/>
        <xs:attribute name="maxActive" type="xs:integer" default="10"/>
        <xs:attribute name="maxWaitMillion" type="xs:integer" default="3000"/>
    </xs:complexType>

    <xs:complexType name="Config">
        <xs:sequence>
            <xs:element ref="database"/>
            <xs:element ref="data-source" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== HarveyBlocks/your-batis/YourBatis-core/src/test/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns="http://batis.harvey.org/schema/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://batis.harvey.org/schema/config
                            https://batis.harvey.org/schema/config/yourbatis-config.xsd">
    <transactionManager type="org.harvey.batis.transaction.jdbc.JdbcTransactionFactory"/>
    <database type="org.harvey.batis.datasource.UnpooledDataSourceFactory">
        <url>
            <protocol>jdbc:mysql</protocol>
            <host>redis</host>
            <port>3306</port>
            <database-name>employee</database-name>
        </url>
        <auth>
            <username>root</username>
            <password>123456</password>
        </auth>
    </database>
    <datasource>
        <initialSize>5</initialSize>
        <maxActive>10</maxActive>
        <maxWaitMillion>3000</maxWaitMillion>
    </datasource>

</config>

=== HarveyBlocks/your-batis/YourBatis-core/src/main/resources/YourBatis-config.xml
<?xml version="1.0" encoding="UTF-8"?>


<config xmlns="http://batis.harvey.org/schema/config"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://batis.harvey.org/schema/config
                            https://batis.harvey.org/schema/config/YourBatis-config.xsd">
    <database>
        <url>
            <database-name>employee</database-name>
            <host>redis</host>
            <port>3306</port>
        </url>
        <auth>
            <username>root</username>
            <password>123456</password>
        </auth>
    </database>
    <data-source>
        <initialSize>5</initialSize>
        <maxActive>10</maxActive>
        <maxWaitMillion>3000</maxWaitMillion>
    </data-source>
</config>
